name: star_counter
description: Count the number of stars in a respository. Built with Love by Geektutor.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.3.0
  github: ^6.1.0
  intl: ^0.16.0
  url_launcher: ^5.4.0

flutter:
  uses-material-design: true